import {
  FaUser,
  FaMicrophone,
  FaPaperPlane,
  FaUsers,
  FaUserPlus,
  FaAngleRight,
  FaGithub,
  FaPhone,
} from "react-icons/fa";
import { FaArrowDownUpAcrossLine } from "react-icons/fa6";
import { BsFillGridFill } from "react-icons/bs";
import {
  HiOutlineViewBoards,
  HiOutlineViewGridAdd,
  HiOutlineDocumentText,
  HiClipboardCheck,
} from "react-icons/hi";
import { MdOutlineListAlt, MdShoppingBasket } from "react-icons/md";
import { LuDiamondPlus, LuShieldAlert } from "react-icons/lu";
import { HiOutlineChartBar } from "react-icons/hi2"; // مثال أيقونة chart
import { BiSolidBadgeCheck } from "react-icons/bi";
import { RiFileChartLine } from "react-icons/ri";

export const data = [
  {
    icon: FaUser,
    title: "Profile",
  },
  {
    icon: FaMicrophone,
    title: "Billing",
  },
  {
    icon: FaPaperPlane,
    title: "Settings",
  },
  {
    icon: FaArrowDownUpAcrossLine,
    title: "Keyboard Shortcuts",
  },
];

export const data_2 = [
  {
    title: "team",
    icon: FaUsers,
  },
  {
    title: "invite User",
    icon: FaUserPlus,
    icon_2: FaAngleRight,
    hoverlinks: ["Email", "Message", "Facebook"],
  },
  {
    title: "Github",
    icon: FaGithub,
  },
  {
    title: "Support",
    icon: FaPhone,
    icon_2: FaAngleRight,
    hoverlinks: ["portal", "slack", "Whatsapp"],
  },
];

export const sidebardetailes = [
  {
    title: "Dashbord",
    icon: BsFillGridFill,
    path: "/dashbord",
  },
  {
    title: "Users",
    icon: FaUsers,
    path: "/dashbord/users",
  },
  {
    title: "Add User",
    icon: FaUserPlus,
    path: "/dashbord/adduser",
  },
  {
    title: "Categories",
    icon: HiOutlineViewBoards,
    path: "/dashbord/categories",
  },
  {
    title: "Add Category",
    icon: HiOutlineViewGridAdd,
    path: "/dashbord/addcategory",
  },
  {
    title: "Products",
    icon: MdOutlineListAlt,
    path: "/dashbord/products",
  },
  {
    title: "Add Product",
    icon: LuDiamondPlus,
    path: "/dashbord/addproduct",
  },
  {
    title: "Orders",
    icon: MdShoppingBasket,
    path: "/dashbord/orders",
  },
  {
    title: "Vendors",
    icon: HiOutlineDocumentText,
    path: "/dashbord/vendors",
  },
  {
    title: "Add Vendor",
    icon: HiClipboardCheck,
    path: "/dashbord/addvendor",
  },
];

export const fourcards = [
  {
    text: "Total Sales",
    number: "42,750.98",
    icon: HiOutlineChartBar,
    bg_color: "#4e33b8",
  },
  {
    text: "Today Orders",
    number: "536,23,3",
    icon: RiFileChartLine,
    bg_color: "#f97316",
  },
  {
    text: "Completed Orders",
    number: "234,1",
    icon: BiSolidBadgeCheck,
    bg_color: "#22c55e",
  },
  {
    text: "Pending Orders",
    number: "332,34",
    icon: LuShieldAlert,
    bg_color: "#ef4444",
  },
];

export const users = [
  {
    id: "#546936",
    name: "Prantik Chakraborty",
    created_at: "21 Jan 2024",
    money: "$8,863",
    email: "bellas@gmail.com",
    posation: "1",
    score: "90%",
    imgsrc: "/dashbord/avatar-2.jpg",
    color: "red-400",
  },
  {
    id: "#546936",
    name: "Prantik Chakraborty",
    created_at: "21 Jan 2024",
    money: "$8,863",
    email: "bellas@gmail.com",
    posation: "1",
    score: "90%",
    imgsrc: "/dashbord/avatar-3.jpg",
    color: "red-400",
  },
  {
    id: "#546936",
    name: "Prantik Chakraborty",
    created_at: "21 Jan 2024",
    money: "$7,863",
    email: "bellas@gmail.com",
    posation: "2",
    score: "80%",
    imgsrc: "/dashbord/avatar-4.jpg",
    color: "green-400",
  },
  {
    id: "#546936",
    name: "Prantik Chakraborty",
    created_at: "21 Jan 2024",
    money: "$6,863",
    email: "bellas@gmail.com",
    posation: "3",
    score: "70%",
    imgsrc: "/dashbord/avatar-5.jpg",
    color: "yellow-400",
  },
  {
    id: "#546936",
    name: "Prantik Chakraborty",
    created_at: "21 Jan 2024",
    money: "$5,863",
    email: "bellas@gmail.com",
    posation: "4",
    score: "66%",
    imgsrc: "/dashbord/avatar-6.jpg",
    color: "sky-400",
  },
  {
    id: "#546936",
    name: "Prantik Chakraborty",
    created_at: "21 Jan 2024",
    money: "$5,863",
    email: "bellas@gmail.com",
    posation: "4",
    score: "66%",
    imgsrc: "/dashbord/avatar-2.jpg",
    color: "sky-400",
  },
  {
    id: "#546936",
    name: "Prantik Chakraborty",
    created_at: "21 Jan 2024",
    money: "$5,863",
    email: "bellas@gmail.com",
    posation: "4",
    score: "66%",
    imgsrc: "/dashbord/avatar-5.jpg",
    color: "sky-400",
  },
  {
    id: "#546936",
    name: "Prantik Chakraborty",
    created_at: "21 Jan 2024",
    money: "$5,863",
    email: "bellas@gmail.com",
    posation: "4",
    score: "66%",
    imgsrc: "/dashbord/avatar-6.jpg",
    color: "sky-400",
  },
  {
    id: "#546936",
    name: "Prantik Chakraborty",
    created_at: "21 Jan 2024",
    money: "$5,863",
    email: "bellas@gmail.com",
    posation: "4",
    score: "66%",
    imgsrc: "/dashbord/avatar-3.jpg",
    color: "sky-400",
  },
  {
    id: "#546936",
    name: "Prantik Chakraborty",
    created_at: "21 Jan 2024",
    money: "$4,863",
    email: "bellas@gmail.com",
    posation: "5",
    score: "64%",
    imgsrc: "/dashbord/avatar-7.jpg",
  },
  {
    id: "#546936",
    name: "Prantik Chakraborty",
    created_at: "21 Jan 2024",
    money: "$3,863",
    email: "bellas@gmail.com",
    posation: "6",
    score: "55%",
    imgsrc: "/dashbord/avatar-8.jpg",
  },
  {
    id: "#546936",
    name: "Prantik Chakraborty",
    created_at: "21 Jan 2024",
    money: "$2,863",
    email: "bellas@gmail.com",
    posation: "7",
    score: "33%",
    imgsrc: "/dashbord/avatar-2.jpg",
  },
  {
    id: "#546936",
    name: "Prantik Chakraborty",
    created_at: "21 Jan 2024",
    money: "$2,263",
    email: "bellas@gmail.com",
    posation: "8",
    score: "31%",
    imgsrc: "/dashbord/avatar-4.jpg",
  },
  {
    id: "#546936",
    name: "Prantik Chakraborty",
    created_at: "21 Jan 2024",
    money: "$1,863",
    email: "bellas@gmail.com",
    posation: "9",
    score: "20%",
    imgsrc: "/dashbord/avatar-5.jpg",
  },
];

export const fourusers = [
  {
    id: "#546936",
    name: "Prantik Chakraborty",
    created_at: "21 Jan 2024",
    money: "$8,863",
    email: "bellas@gmail.com",
    posation: "1",
    score: "90%",
    imgsrc: "/dashbord/avatar-2.jpg",
    color: "red-400",
  },
  {
    id: "#546936",
    name: "Prantik Chakraborty",
    created_at: "21 Jan 2024",
    money: "$7,863",
    email: "bellas@gmail.com",
    posation: "2",
    score: "80%",
    imgsrc: "/dashbord/avatar-4.jpg",
    color: "green-400",
  },
  {
    id: "#546936",
    name: "Prantik Chakraborty",
    created_at: "21 Jan 2024",
    money: "$6,863",
    email: "bellas@gmail.com",
    posation: "3",
    score: "70%",
    imgsrc: "/dashbord/avatar-5.jpg",
    color: "yellow-400",
  },
  {
    id: "#546936",
    name: "Prantik Chakraborty",
    created_at: "21 Jan 2024",
    money: "$5,863",
    email: "bellas@gmail.com",
    posation: "4",
    score: "66%",
    imgsrc: "/dashbord/avatar-6.jpg",
    color: "sky-400",
  },
];

export const TopThree = [
  {
    id: "#546936",
    name: "Prantik Chakraborty",
    created_at: "21 Jan 2024",
    money: "$7,863",
    email: "bellas@gmail.com",
    posation: "2",
    score: "80%",
    imgsrc: "/dashbord/avatar-2.jpg",
  },
  {
    id: "#546936",
    name: "Prantik Chakraborty",
    created_at: "21 Jan 2024",
    money: "$8,863",
    email: "bellas@gmail.com",
    posation: "1",
    score: "90%",
    imgsrc: "/dashbord/avatar-4.jpg",
  },
  {
    id: "#546936",
    name: "Prantik Chakraborty",
    created_at: "21 Jan 2024",
    money: "$6,863",
    email: "bellas@gmail.com",
    posation: "3",
    score: "70%",
    imgsrc: "/dashbord/avatar-5.jpg",
  },
];

export const TopSellproducts = [
  {
    title: "Apple red watch",
    imgsrc: "/dashbord/image_60.jpg",
    price: "$369.36",
    sales: "936",
  },
  {
    title: "Apple red watch",
    imgsrc: "/dashbord/image_61.jpg",
    price: "$369.36",
    sales: "936",
  },
  {
    title: "Apple red watch",
    imgsrc: "/dashbord/image_62.jpg",
    price: "$369.36",
    sales: "936",
  },
  {
    title: "Apple red watch",
    imgsrc: "/dashbord/image_63.jpg",
    price: "$369.36",
    sales: "936",
  },
  {
    title: "Apple red watch",
    imgsrc: "/dashbord/image_64.jpg",
    price: "$369.36",
    sales: "936",
  },
  {
    title: "Apple red watch",
    imgsrc: "/dashbord/image_65.jpg",
    price: "$369.36",
    sales: "936",
  },
  {
    title: "Apple red watch",
    imgsrc: "/dashbord/image_66.jpg",
    price: "$369.36",
    sales: "936",
  },
  {
    title: "Apple red watch",
    imgsrc: "/dashbord/image_67.jpg",
    price: "$369.36",
    sales: "936",
  },
  {
    title: "Apple red watch",
    imgsrc: "/dashbord/image_68.jpg",
    price: "$369.36",
    sales: "936",
  },
  {
    title: "Apple red watch",
    imgsrc: "/dashbord/image_69.jpg",
    price: "$369.36",
    sales: "936",
  },
  {
    title: "Apple red watch",
    imgsrc: "/dashbord/image_70.jpg",
    price: "$369.36",
    sales: "936",
  },
  {
    title: "Apple red watch",
    imgsrc: "/dashbord/image_71.jpg",
    price: "$369.36",
    sales: "936",
  },
  {
    title: "Apple red watch",
    imgsrc: "/dashbord/image_72.jpg",
    price: "$369.36",
    sales: "936",
  },
  {
    title: "Apple red watch",
    imgsrc: "/dashbord/image_73.jpg",
    price: "$369.36",
    sales: "936",
  },
];

export const ordersdetails = [
  {
    invoice: "#99652",
    username: "Prantik Chakraborty",
    date: "21 Jan 2024",
    price: "$996.20",
    status: false,
  },
  {
    invoice: "#99652",
    username: "Prantik Chakraborty",
    date: "21 Jan 2024",
    price: "$996.20",
    status: true,
  },
  {
    invoice: "#99652",
    username: "Prantik Chakraborty",
    date: "21 Jan 2024",
    price: "$996.20",
    status: false,
  },
  {
    invoice: "#99652",
    username: "Prantik Chakraborty",
    date: "21 Jan 2024",
    price: "$996.20",
    status: true,
  },
  {
    invoice: "#99652",
    username: "Prantik Chakraborty",
    date: "21 Jan 2024",
    price: "$996.20",
    status: false,
  },
  {
    invoice: "#99652",
    username: "Prantik Chakraborty",
    date: "21 Jan 2024",
    price: "$996.20",
    status: false,
  },
  {
    invoice: "#99652",
    username: "Prantik Chakraborty",
    date: "21 Jan 2024",
    price: "$996.20",
    status: false,
  },
  {
    invoice: "#99652",
    username: "Prantik Chakraborty",
    date: "21 Jan 2024",
    price: "$996.20",
    status: true,
  },
  {
    invoice: "#99652",
    username: "Prantik Chakraborty",
    date: "21 Jan 2024",
    price: "$996.20",
    status: true,
  },
  {
    invoice: "#99652",
    username: "Prantik Chakraborty",
    date: "21 Jan 2024",
    price: "$996.20",
    status: true,
  },
  {
    invoice: "#99652",
    username: "Prantik Chakraborty",
    date: "21 Jan 2024",
    price: "$996.20",
    status: false,
  },
  {
    invoice: "#99652",
    username: "Prantik Chakraborty",
    date: "21 Jan 2024",
    price: "$996.20",
    status: false,
  },
  {
    invoice: "#99652",
    username: "Prantik Chakraborty",
    date: "21 Jan 2024",
    price: "$996.20",
    status: false,
  },
  {
    invoice: "#99652",
    username: "Prantik Chakraborty",
    date: "21 Jan 2024",
    price: "$996.20",
    status: false,
  },
  {
    invoice: "#99652",
    username: "Prantik Chakraborty",
    date: "21 Jan 2024",
    price: "$996.20",
    status: true,
  },
  {
    invoice: "#99652",
    username: "Prantik Chakraborty",
    date: "21 Jan 2024",
    price: "$996.20",
    status: false,
  },
  {
    invoice: "#99652",
    username: "Prantik Chakraborty",
    date: "21 Jan 2024",
    price: "$996.20",
    status: false,
  },
  {
    invoice: "#99652",
    username: "Prantik Chakraborty",
    date: "21 Jan 2024",
    price: "$996.20",
    status: false,
  },
  {
    invoice: "#99652",
    username: "Prantik Chakraborty",
    date: "21 Jan 2024",
    price: "$996.20",
    status: true,
  },
  {
    invoice: "#99652",
    username: "Prantik Chakraborty",
    date: "21 Jan 2024",
    price: "$996.20",
    status: false,
  },
  {
    invoice: "#99652",
    username: "Prantik Chakraborty",
    date: "21 Jan 2024",
    price: "$996.20",
    status: false,
  },
  {
    invoice: "#99652",
    username: "Prantik Chakraborty",
    date: "21 Jan 2024",
    price: "$996.20",
    status: true,
  },
];

export const usersdata = [
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "John Smith",
    account: "john.smith",
    creation_date: "2023-01-01",
    image: "/dashbord/user-1.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Jane Doe",
    account: "jane.doe",
    creation_date: "2023-01-02",
    image: "/dashbord/user-2.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Michael Brown",
    account: "michael.brown",
    creation_date: "2023-01-03",
    image: "/dashbord/user-3.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Emily Davis",
    account: "emily.davis",
    creation_date: "2023-01-04",
    image: "/dashbord/user-4.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Chris Johnson",
    account: "chris.johnson",
    creation_date: "2023-01-05",
    image: "/dashbord/user-5.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Jessica Wilson",
    account: "jessica.wilson",
    creation_date: "2023-01-06",
    image: "/dashbord/user-1.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "David Martinez",
    account: "david.martinez",
    creation_date: "2023-01-07",
    image: "/dashbord/user-2.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Sarah Garcia",
    account: "sarah.garcia",
    creation_date: "2023-01-08",
    image: "/dashbord/user-3.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Daniel Rodriguez",
    account: "daniel.rodriguez",
    creation_date: "2023-01-09",
    image: "/dashbord/user-4.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Laura Hernandez",
    account: "laura.hernandez",
    creation_date: "2023-01-10",
    image: "/dashbord/user-5.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Matthew Lee",
    account: "matthew.lee",
    creation_date: "2023-01-11",
    image: "/dashbord/user-1.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Olivia Walker",
    account: "olivia.walker",
    creation_date: "2023-01-12",
    image: "/dashbord/user-2.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "James Hall",
    account: "james.hall",
    creation_date: "2023-01-13",
    image: "/dashbord/user-3.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Sophia Young",
    account: "sophia.young",
    creation_date: "2023-01-14",
    image: "/dashbord/user-4.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Benjamin Allen",
    account: "benjamin.allen",
    creation_date: "2023-01-15",
    image: "/dashbord/user-5.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Mia King",
    account: "mia.king",
    creation_date: "2023-01-16",
    image: "/dashbord/user-1.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Jacob Wright",
    account: "jacob.wright",
    creation_date: "2023-01-17",
    image: "/dashbord/user-2.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Charlotte Scott",
    account: "charlotte.scott",
    creation_date: "2023-01-18",
    image: "/dashbord/user-3.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Ethan Green",
    account: "ethan.green",
    creation_date: "2023-01-19",
    image: "/dashbord/user-4.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Abigail Adams",
    account: "abigail.adams",
    creation_date: "2023-01-20",
    image: "/dashbord/user-5.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Alexander Baker",
    account: "alexander.baker",
    creation_date: "2023-01-21",
    image: "/dashbord/user-1.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Ava Nelson",
    account: "ava.nelson",
    creation_date: "2023-01-22",
    image: "/dashbord/user-2.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "William Carter",
    account: "william.carter",
    creation_date: "2023-01-23",
    image: "/dashbord/user-3.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Isabella Mitchell",
    account: "isabella.mitchell",
    creation_date: "2023-01-24",
    image: "/dashbord/user-4.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Logan Perez",
    account: "logan.perez",
    creation_date: "2023-01-25",
    image: "/dashbord/user-5.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Sofia Roberts",
    account: "sofia.roberts",
    creation_date: "2023-01-26",
    image: "/dashbord/user-1.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Jackson Turner",
    account: "jackson.turner",
    creation_date: "2023-01-27",
    image: "/dashbord/user-2.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Avery Phillips",
    account: "avery.phillips",
    creation_date: "2023-01-28",
    image: "/dashbord/user-3.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Mason Campbell",
    account: "mason.campbell",
    creation_date: "2023-01-29",
    image: "/dashbord/user-4.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Chloe Parker",
    account: "chloe.parker",
    creation_date: "2023-01-30",
    image: "/dashbord/user-5.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Henry Evans",
    account: "henry.evans",
    creation_date: "2023-01-31",
    image: "/dashbord/user-1.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Ella Edwards",
    account: "ella.edwards",
    creation_date: "2023-02-01",
    image: "/dashbord/user-2.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Daniel Collins",
    account: "daniel.collins",
    creation_date: "2023-02-02",
    image: "/dashbord/user-3.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Grace Stewart",
    account: "grace.stewart",
    creation_date: "2023-02-03",
    image: "/dashbord/user-4.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Wyatt Sanchez",
    account: "wyatt.sanchez",
    creation_date: "2023-02-04",
    image: "/dashbord/user-5.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Lily Morris",
    account: "lily.morris",
    creation_date: "2023-02-05",
    image: "/dashbord/user-1.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Owen Rivera",
    account: "owen.rivera",
    creation_date: "2023-02-06",
    image: "/dashbord/user-2.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Scarlett Cooper",
    account: "scarlett.cooper",
    creation_date: "2023-02-07",
    image: "/dashbord/user-3.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Jack Reed",
    account: "jack.reed",
    creation_date: "2023-02-08",
    image: "/dashbord/user-4.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Mila Cook",
    account: "mila.cook",
    creation_date: "2023-02-09",
    image: "/dashbord/user-5.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Elijah Morgan",
    account: "elijah.morgan",
    creation_date: "2023-02-10",
    image: "/dashbord/user-1.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Zoey Bell",
    account: "zoey.bell",
    creation_date: "2023-02-11",
    image: "/dashbord/user-2.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Gabriel Murphy",
    account: "gabriel.murphy",
    creation_date: "2023-02-12",
    image: "/dashbord/user-3.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Nora Bailey",
    account: "nora.bailey",
    creation_date: "2023-02-13",
    image: "/dashbord/user-4.png",
  },
  {
    id: (Math.random() * 100)?.toFixed(0),
    name: "Luke Rivera",
    account: "luke.rivera",
    creation_date: "2023-02-14",
    image: "/dashbord/user-5.png",
  },
];

export const categoriesdata = [
  { id: 1, title: "Category 1 - Item 1", image: "/dashbord/category-1.png" },
  { id: 2, title: "Category 1 - Item 2", image: "/dashbord/category-1.png" },
  { id: 3, title: "Category 1 - Item 3", image: "/dashbord/category-1.png" },
  { id: 4, title: "Category 1 - Item 4", image: "/dashbord/category-1.png" },
  { id: 5, title: "Category 1 - Item 5", image: "/dashbord/category-1.png" },

  { id: 6, title: "Category 2 - Item 1", image: "/dashbord/category-2.png" },
  { id: 7, title: "Category 2 - Item 2", image: "/dashbord/category-2.png" },
  { id: 8, title: "Category 2 - Item 3", image: "/dashbord/category-2.png" },
  { id: 9, title: "Category 2 - Item 4", image: "/dashbord/category-2.png" },
  { id: 10, title: "Category 2 - Item 5", image: "/dashbord/category-2.png" },

  { id: 11, title: "Category 3 - Item 1", image: "/dashbord/category-3.png" },
  { id: 12, title: "Category 3 - Item 2", image: "/dashbord/category-3.png" },
  { id: 13, title: "Category 3 - Item 3", image: "/dashbord/category-3.png" },
  { id: 14, title: "Category 3 - Item 4", image: "/dashbord/category-3.png" },
  { id: 15, title: "Category 3 - Item 5", image: "/dashbord/category-3.png" },

  { id: 16, title: "Category 4 - Item 1", image: "/dashbord/category-4.png" },
  { id: 17, title: "Category 4 - Item 2", image: "/dashbord/category-4.png" },
  { id: 18, title: "Category 4 - Item 3", image: "/dashbord/category-4.png" },
  { id: 19, title: "Category 4 - Item 4", image: "/dashbord/category-4.png" },
  { id: 20, title: "Category 4 - Item 5", image: "/dashbord/category-4.png" },

  { id: 21, title: "Category 5 - Item 1", image: "/dashbord/category-5.png" },
  { id: 22, title: "Category 5 - Item 2", image: "/dashbord/category-5.png" },
  { id: 23, title: "Category 5 - Item 3", image: "/dashbord/category-5.png" },
  { id: 24, title: "Category 5 - Item 4", image: "/dashbord/category-5.png" },
  { id: 25, title: "Category 5 - Item 5", image: "/dashbord/category-5.png" },

  { id: 26, title: "Category 1 - Item 6", image: "/dashbord/category-1.png" },
  { id: 27, title: "Category 1 - Item 7", image: "/dashbord/category-1.png" },
  { id: 28, title: "Category 1 - Item 8", image: "/dashbord/category-1.png" },
  { id: 29, title: "Category 1 - Item 9", image: "/dashbord/category-1.png" },
  { id: 30, title: "Category 1 - Item 10", image: "/dashbord/category-1.png" },

  { id: 31, title: "Category 2 - Item 6", image: "/dashbord/category-2.png" },
  { id: 32, title: "Category 2 - Item 7", image: "/dashbord/category-2.png" },
  { id: 33, title: "Category 2 - Item 8", image: "/dashbord/category-2.png" },
  { id: 34, title: "Category 2 - Item 9", image: "/dashbord/category-2.png" },
  { id: 35, title: "Category 2 - Item 10", image: "/dashbord/category-2.png" },

  { id: 36, title: "Category 3 - Item 6", image: "/dashbord/category-3.png" },
  { id: 37, title: "Category 3 - Item 7", image: "/dashbord/category-3.png" },
  { id: 38, title: "Category 3 - Item 8", image: "/dashbord/category-3.png" },
  { id: 39, title: "Category 3 - Item 9", image: "/dashbord/category-3.png" },
  { id: 40, title: "Category 3 - Item 10", image: "/dashbord/category-3.png" },

  { id: 41, title: "Category 4 - Item 6", image: "/dashbord/category-4.png" },
  { id: 42, title: "Category 4 - Item 7", image: "/dashbord/category-4.png" },
  { id: 43, title: "Category 4 - Item 8", image: "/dashbord/category-4.png" },
  { id: 44, title: "Category 4 - Item 9", image: "/dashbord/category-4.png" },
  { id: 45, title: "Category 4 - Item 10", image: "/dashbord/category-4.png" },

  { id: 46, title: "Category 5 - Item 6", image: "/dashbord/category-5.png" },
  { id: 47, title: "Category 5 - Item 7", image: "/dashbord/category-5.png" },
  { id: 48, title: "Category 5 - Item 8", image: "/dashbord/category-5.png" },
  { id: 49, title: "Category 5 - Item 9", image: "/dashbord/category-5.png" },
  { id: 50, title: "Category 5 - Item 10", image: "/dashbord/category-5.png" },
];
